blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

add_article:
    path: /add
    defaults: { _controller: BlogBundle:Default:add}

show:
    path: /{id}
    defaults:
        _controller : BlogBundle:Default:show
    requirements:
            id: \d+